package com.phatpl.metube.common.api;

public enum ApiErrorCode {
  AUTHENTICATION_REQUIRED,
  INVALID_ACCESS_TOKEN,
  INVALID_TOKEN_TYPE,
  TOKEN_VERSION_MISMATCH,
  USER_DISABLED,
  ACCESS_DENIED,
  INTERNAL_SERVER_ERROR,
  USERNAME_TAKEN,
  EMAIL_TAKEN,
  INVALID_CREDENTIALS,
  ACCOUNT_DISABLED,
  EMAIL_NOT_VERIFIED,
  INVALID_VERIFICATION_TOKEN,
  CAPTCHA_REQUIRED,
  CAPTCHA_INVALID,
  RATE_LIMITED,
  VALIDATION_FAILED,
  INVALID_REFRESH_TOKEN
}