package com.phatpl.metube.common.api;

public enum ApiErrorCode {
  AUTHENTICATION_REQUIRED,
  INVALID_ACCESS_TOKEN,
  INVALID_TOKEN_TYPE,
  TOKEN_VERSION_MISMATCH,
  USER_DISABLED,
  ACCESS_DENIED,
  INTERNAL_SERVER_ERROR
}